POST http://127.0.0.1:8000/generate
Content-Type: application/json

{
    "prompt" : "저는 甲회사에 입사하여 5년째 되던 해 소속부서 업무가 乙회사로 독립되자 甲회사에서 일방적으로 근로자들을 일괄 사직처리하고 퇴직금을 수령하도록 한 후, 그 다음 날짜로 乙회사에 입사한 것으로 하였습니다. 그 후 제가 乙회사를 퇴직하게 되자 乙회사에서는 乙회사 근무기간 4년 9개월에 해당되는 퇴직금만을 지급하겠다고 합니다. 이 경우 甲회사에 입사한 때부터 乙회사에서 퇴직할 때까지의 기간을 계속근로연수로 하여 지급배수를 정한 누진퇴직금을 받을 수는 없는지요?",
    "based_on_semantic_search" : true
}
###

GET http://127.0.0.1:8000/api/api